**Numpy**

In [ ]:
a=[1,2,3]
b=[4,5,6]


In [ ]:
a+b

[1, 2, 3, 4, 5, 6]

In [ ]:
import numpy as np
a=np.array([1,2,3])

In [ ]:
b=np.array([4,5,6])

In [ ]:
a+b

array([5, 7, 9])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
a[0]=3.9
print(a)
a=a.astype('float64')

[3.9 2.  3. ]


In [ ]:
a.dtype

dtype('float64')

In [ ]:
a

array([3.9, 2. , 3. ])

In [ ]:
arr2d=np.array([[1,2,3],[3,4,5]])
print("shape : " ,arr2d.shape)
print("dimension : ",arr2d.ndim)
print("size : ",arr2d.size)

shape :  (2, 3)
dimension :  2
size :  6


In [ ]:
arr2d.ndim

2

In [ ]:
arr2d.size

6

In [ ]:
arr3d=np.array([[[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]]])


(2, 2, 3)


In [ ]:
arr3d[0,0]

array([1, 2, 3])

In [ ]:
print("shape : " ,arr3d.shape)
print("dimension : ",arr3d.ndim)
print("size : ",arr3d.size)

shape :  (2, 2, 3)
dimension :  3
size :  12


In [ ]:
a*b

array([15.6, 10. , 18. ])

In [ ]:
a**b

array([231.3441,  32.    , 729.    ])

In [ ]:
#mathematical function
np.sin(a)
#everything is vectorised in numpy


array([-0.68776616,  0.90929743,  0.14112001])

In [ ]:
def print_info(a):
  print("Shape : " ,a.shape)
  print("Data type : ",a.dtype)
  print("Number of elements : ",a.size)
  print("Strides : ",a.strides)

In [ ]:
print_info(arr2d)

Shape :  (2, 3)
Data type :  int64
Number of elements :  6
Strides :  (24, 8)


In [ ]:
arr2d[0,0]

1

In [ ]:
arr2d[:,0]
#element of firat column

array([1, 3])

In [ ]:
arr2d

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
arr3d[:,0]

array([[1, 2, 3],
       [6, 7, 8]])

In [ ]:
arr3d[0][1][1]

4

In [ ]:
print_info(arr3d)

Shape :  (2, 2, 3)
Data type :  int64
Number of elements :  12
Strides :  (48, 24, 8)


**Slicing**

    var[lower:upper:step]
The upper index is not included. The lower is included
    var[:]==everything
    var[:3]==everything till 3
    var[:,3]==everything of 1st dim and 4th col of second dim

In [ ]:
arr3d[:,1]#from every 2d array and first element of  2d array

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [ ]:
arr3d[:][1]
arr3d

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
temp=np.arange(10).reshape(5,2)
temp
arr4=np.arange(25).reshape(5,5)

In [ ]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr4[4]

array([20, 21, 22, 23, 24])

In [ ]:
arr4[:,1:5:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [ ]:
arr4[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [ ]:
# Image is a 2 d numpy array
import matplotlib.pyplot as plt
import matplotlib.image as img


In [ ]:
testImage = img.imread('input_image.jpg')
testImage.ndim

2

In [ ]:
testImage[:]

array([[157, 157, 157, ..., 151, 153, 155],
       [158, 158, 158, ..., 154, 154, 154],
       [159, 159, 159, ..., 156, 154, 153],
       ...,
       [109, 127, 130, ..., 140, 128, 111],
       [129, 115, 120, ..., 139, 134, 113],
       [119, 137, 118, ..., 127, 134, 112]], dtype=uint8)

In [ ]:
testImage.shape

(256, 256)

In [ ]:
temp=np.arange().reshape(255,255)

ValueError: ignored